[Server]
host="localhost"
port=14300
ssl=false

[log]
access_log="access.log"
error_log="error.log"

[[route]]
channel="waiwai"
path="http://localhost:8080"

[[route]]
channel="waiwaigayagaya"
path="http://localhost:8080"

[[route]]
channel="primus_dev"
path="http://localhost:8080"
